# Generated by Django 4.2.8 on 2025-06-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprovider',
            options={'verbose_name': 'SMS Provider', 'verbose_name_plural': 'SMS Providers'},
        ),
        migrations.RemoveField(
            model_name='smsprovider',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='smsprovider',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='smsprovider',
            name='config',
        ),
        migrations.RemoveField(
            model_name='smsprovider',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='smsprovider',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='api_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='api_url',
            field=models.URLField(blank=True, help_text='API endpoint URL'),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='provider_type',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('nexmo', 'Nexmo'), ('messagebird', 'MessageBird'), ('ssl_wireless', 'SSL Wireless'), ('custom', 'Custom API')], default='ssl_wireless', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='sid',
            field=models.CharField(blank=True, help_text='Sender ID/Masking name', max_length=50),
        ),
    ]
