# Generated by Django 4.2.8 on 2025-06-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_smsprovider_options_remove_smsprovider_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprovider',
            name='api_url',
            field=models.URLField(blank=True, help_text='API endpoint URL (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='sid',
            field=models.CharField(blank=True, help_text='Sender ID/Masking name (optional)', max_length=50, null=True),
        ),
    ]
