# Generated by Django 4.2.8 on 2025-06-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_smsprovider_api_url_alter_smsprovider_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_status_change', 'Order Status Changed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('emi_created', 'EMI Created'), ('emi_application_submitted', 'EMI Application Submitted'), ('emi_approved', 'EMI Approved'), ('emi_rejected', 'EMI Rejected'), ('emi_payment_due', 'EMI Payment Due'), ('emi_payment_received', 'EMI Payment Received'), ('emi_payment_late', 'EMI Payment Late'), ('user_registered', 'User Registered'), ('password_reset', 'Password Reset'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('low_stock', 'Low Stock Alert')], max_length=50),
        ),
    ]
