# Generated by Django 4.2 on 2024-06-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='type',
            field=models.CharField(choices=[('welcome', 'Welcome Message'), ('verification', 'Phone Verification'), ('order_confirmation', 'Order Confirmation'), ('order_created', 'Order Created'), ('payment_success', 'Payment Success'), ('order_status', 'Order Status Update'), ('emi_reminder', 'EMI Payment Reminder'), ('emi_application_submitted', 'EMI Application Submitted')], max_length=50),
        ),
    ] 