# Generated by Django 4.2.8 on 2025-05-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emirecord',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='emirecord',
            name='income_proof',
            field=models.FileField(blank=True, null=True, upload_to='emi_documents/income/'),
        ),
        migrations.AddField(
            model_name='emirecord',
            name='nid_document',
            field=models.FileField(blank=True, null=True, upload_to='emi_documents/nid/'),
        ),
        migrations.AddField(
            model_name='emirecord',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emirecord',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emirecord',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='emirecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_emis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emirecord',
            name='job_type',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business', 'Business Owner'), ('student', 'Student'), ('unemployed', 'Unemployed'), ('other', 'Other')], default='salaried', max_length=20),
        ),
    ]
