# Generated by Django 4.2.8 on 2025-05-26 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_remove_emirecord_is_verified_emirecord_income_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emirecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_emi_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
