# Generated by Django 4.2.8 on 2025-05-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_emirecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emirecord',
            name='order',
        ),
        migrations.RemoveField(
            model_name='emirecord',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='emirecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emirecord',
            name='verified_by',
        ),
        migrations.DeleteModel(
            name='EMIPayment',
        ),
        migrations.DeleteModel(
            name='EMIPlan',
        ),
        migrations.DeleteModel(
            name='EMIRecord',
        ),
    ]
