# Generated by Django 5.2.1 on 2025-06-04 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cartitem_unique_together_cartitem_variation_and_more'),
        ('products', '0004_pricemodifier_productvariation_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariation'),
        ),
    ]
