# Generated by Django 5.2.1 on 2025-06-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0005_emiplan_is_sslcommerz_emi_and_more'),
        ('orders', '0009_orderitem_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='emi_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='emi.emiplan'),
        ),
    ]
