# Generated by Django 5.2.1 on 2025-06-04 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0005_emiplan_is_sslcommerz_emi_and_more'),
        ('orders', '0010_cartitem_emi_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='emi_plan',
            field=models.ForeignKey(blank=True, help_text='Selected EMI plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emi.emiplan'),
        ),
    ]
