# Generated by Django 4.2.8 on 2025-06-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0008_emiplan_sslcommerz_bank_interest_rates_and_more'),
        ('orders', '0013_cart_discount_amount_cart_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='emi_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emi.emiplan'),
        ),
    ]
