# Generated by Django 4.2.8 on 2025-05-26 15:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_emirecord_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMIApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure_months', models.PositiveIntegerField(help_text='EMI tenure in months', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('employment_type', models.CharField(choices=[('salaried', 'Salaried Employee'), ('self_employed', 'Self Employed'), ('business_owner', 'Business Owner'), ('student', 'Student'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=20)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('years_employed', models.DecimalField(blank=True, decimal_places=1, help_text='Years at current employment', max_digits=4, null=True)),
                ('nid_number', models.CharField(help_text='National ID number', max_length=50)),
                ('nid_front_image', models.ImageField(upload_to='emi/nid_images/')),
                ('nid_back_image', models.ImageField(upload_to='emi/nid_images/')),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='emi/income_proof/')),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='emi/additional_docs/')),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EMIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_months', models.PositiveIntegerField(default=3)),
                ('max_months', models.PositiveIntegerField(default=36)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_price', models.DecimalField(decimal_places=2, default=0, help_text='Minimum product price eligible for this EMI plan', max_digits=10)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum product price eligible for this EMI plan (blank for no limit)', max_digits=10, null=True)),
                ('down_payment_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of product price required as down payment', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Processing fee as percentage of product price', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('processing_fee_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Fixed processing fee amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EMIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure_months', models.PositiveIntegerField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('down_payment_paid', models.BooleanField(default=False)),
                ('installments_paid', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_end_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emi_record', to='emi.emiapplication')),
                ('emi_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='emi.emiplan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emi_record', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_app_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emiapplication',
            name='emi_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='emi.emiplan'),
        ),
        migrations.AddField(
            model_name='emiapplication',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emi_application', to='orders.order'),
        ),
        migrations.AddField(
            model_name='emiapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EMIInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emi_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='emi.emirecord')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('emi_record', 'installment_number')},
            },
        ),
    ]
