# Generated by Django 4.2.8 on 2025-06-01 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emiplan',
            name='max_months',
        ),
        migrations.RemoveField(
            model_name='emiplan',
            name='min_months',
        ),
        migrations.AddField(
            model_name='emiplan',
            name='duration_months',
            field=models.PositiveIntegerField(default=12, help_text='Duration of the EMI plan in months', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='emiplan',
            name='emi_type',
            field=models.CharField(choices=[('normal', 'Normal EMI'), ('cardless', 'Cardless EMI')], default='normal', help_text='Type of EMI plan', max_length=10),
        ),
    ]
