# Generated by Django 4.2.8 on 2025-06-01 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0003_emiplan_max_months_emiplan_min_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emiplan',
            name='max_months',
        ),
        migrations.RemoveField(
            model_name='emiplan',
            name='min_months',
        ),
    ]
