# Generated by Django 4.2.8 on 2025-06-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0004_remove_emiplan_max_months_remove_emiplan_min_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='emiplan',
            name='is_sslcommerz_emi',
            field=models.BooleanField(default=False, help_text="Whether this plan uses SSLCOMMERZ's EMI system"),
        ),
        migrations.AddField(
            model_name='emiplan',
            name='sslcommerz_bank_list',
            field=models.JSONField(blank=True, help_text='List of banks supported for this EMI plan', null=True),
        ),
    ]
