# Generated by Django 5.2.1 on 2025-06-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0005_emiplan_is_sslcommerz_emi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emiplan',
            name='sslcommerz_bank_id',
            field=models.CharField(blank=True, help_text='Bank ID for direct integration with SSLCOMMERZ (optional)', max_length=20, null=True),
        ),
    ]
