# Generated by Django 4.2.8 on 2025-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0007_remove_emiplan_emi_type_emiplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emiplan',
            name='sslcommerz_bank_interest_rates',
            field=models.JSONField(blank=True, help_text="JSON mapping of bank codes to their interest rates (e.g., {'DBBL': 9.5, 'BRAC': 10.0})", null=True),
        ),
        migrations.AlterField(
            model_name='emiplan',
            name='sslcommerz_bank_list',
            field=models.JSONField(blank=True, help_text='List of banks supported for this EMI plan (as array of bank codes)', null=True),
        ),
    ]
