# Generated by Django 4.2.8 on 2025-06-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_fix_specifications'),
        ('products', '0002_initial'),
    ]

    operations = [
    ]
