# Generated by Django 4.2.8 on 2025-06-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0004_remove_emiplan_max_months_remove_emiplan_min_months'),
        ('products', '0003_merge_0002_fix_specifications_0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification_key', models.CharField(max_length=100)),
                ('specification_value', models.CharField(max_length=100)),
                ('modifier_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage'), ('multiplier', 'Multiplier')], default='fixed', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Amount to add/subtract (fixed), percentage to adjust, or multiplier', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_modifiers', to='products.category')),
            ],
            options={
                'ordering': ['category', 'name', 'specification_value'],
                'unique_together': {('category', 'specification_key', 'specification_value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variation name (e.g. '8GB+128GB', '55-inch QLED')", max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default variation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product', '-is_default', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Product variant attributes (color, size, etc.)')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Price adjustment for this variant', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
                'ordering': ['product', 'code'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_emi_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_emi_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price for the product. If variations exist, this will be the minimum price.', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='default_sku',
            field=models.CharField(blank=True, help_text='Main SKU for the product. If not provided, one will be generated.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='emi_plans',
            field=models.ManyToManyField(blank=True, related_name='products', to='emi.emiplan'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_special_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_todays_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productfield',
            name='affects_price',
            field=models.BooleanField(default=False, help_text='Whether this field affects the product price'),
        ),
        migrations.AddField(
            model_name='productfield',
            name='price_modifier_key',
            field=models.CharField(blank=True, help_text="Key to use for price modifiers (e.g., 'storage_capacity', 'screen_size')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='group',
            field=models.CharField(choices=[('general', 'General'), ('specifications', 'Specifications'), ('dimensions', 'Dimensions'), ('display', 'Display'), ('features', 'Features'), ('connectivity', 'Connectivity'), ('hardware', 'Hardware'), ('camera', 'Camera'), ('sensors', 'Sensors'), ('box', 'Box Contents'), ('compartments', 'Compartments'), ('convenience', 'Convenience'), ('pricing', 'Pricing Factors'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.AddField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'name')},
        ),
    ]
