# Generated by Django 4.2 on 2024-06-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_pricemodifier_productvariation_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail_small',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail_medium',
        ),
    ] 