# Generated by Django 4.2 on 2024-06-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_thumbnail_fields'),
        ('products', '0006_add_responsive_images'),
    ]

    operations = [
        # This migration merges the two branches of the migration graph.
        # The thumbnail fields are first removed in 0005_remove_thumbnail_fields
        # and then added back in 0006_add_responsive_images.
    ] 