# Generated by Django 4.2.8 on 2025-06-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_0005_remove_thumbnail_fields_0006_add_responsive_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail_medium',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail_small',
        ),
    ]
