# Generated by Django 4.2.8 on 2025-06-02 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('standard', 'Standard Shipping'), ('express', 'Express Shipping'), ('next_day', 'Next Day Delivery'), ('same_day', 'Same Day Delivery'), ('pickup', 'Local Pickup'), ('freight', 'Freight Shipping')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_delivery_time', models.PositiveIntegerField(default=1, help_text='Minimum delivery time in days')),
                ('max_delivery_time', models.PositiveIntegerField(default=3, help_text='Maximum delivery time in days')),
                ('handling_time', models.PositiveIntegerField(default=1, help_text='Handling/processing time in days')),
                ('requires_signature', models.BooleanField(default=False)),
                ('includes_tracking', models.BooleanField(default=True)),
                ('international_shipping', models.BooleanField(default=False)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in kg', max_digits=10, null=True)),
                ('max_dimensions', models.JSONField(blank=True, help_text='Maximum dimensions (L x W x H) in cm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('countries', models.JSONField(default=list, help_text='List of country codes covered by this zone')),
                ('states', models.JSONField(blank=True, default=list, help_text='List of state/province codes covered by this zone')),
                ('cities', models.JSONField(blank=True, default=list, help_text='List of cities covered by this zone')),
                ('postal_codes', models.JSONField(blank=True, default=list, help_text='List of postal code patterns or ranges covered by this zone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('flat', 'Flat Rate'), ('weight', 'Weight Based'), ('price', 'Order Total Based'), ('item', 'Per Item'), ('dimension', 'Dimensional Weight'), ('combined', 'Combined Factors')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base shipping rate', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=0, help_text='Additional rate per kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_item_rate', models.DecimalField(decimal_places=2, default=0, help_text='Additional rate per item', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order total above which shipping is free', max_digits=10, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions for applying this rate (e.g., weight ranges, price ranges)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['zone', 'method', '-created_at'],
                'unique_together': {('zone', 'method', 'rate_type')},
            },
        ),
    ]
