# Generated by Django 5.2.1 on 2025-06-05 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The main text of the banner, e.g., 'Super Sale 20%'", max_length=50)),
                ('subtitle', models.CharField(help_text="The subtitle of the banner, e.g., 'Only this month'", max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='Icon to display in the banner', null=True, upload_to='promotions/icons/')),
                ('bg_color', models.CharField(default='#333d4cb2', help_text='Background color for the icon circle', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority order (lowest number shows first)')),
            ],
            options={
                'verbose_name': 'Header Promo Banner',
                'verbose_name_plural': 'Header Promo Banners',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='promotions/hero/')),
                ('bg_color', models.CharField(default='bg-blue-100', help_text='Background color class', max_length=50)),
                ('button_text', models.CharField(default='Shop now', max_length=50)),
                ('button_link', models.CharField(default='#', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority order (lowest number shows first)')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='NewArrivalsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MacBook', max_length=100)),
                ('subtitle', models.CharField(default='Be Pro Anywhere', max_length=200)),
                ('image', models.ImageField(upload_to='promotions/new_arrivals/')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='promotions/backgrounds/')),
                ('price_text', models.CharField(default='From ৳1,199', max_length=50)),
                ('button_link', models.CharField(default='#', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'New Arrivals Banner',
                'verbose_name_plural': 'New Arrivals Banners',
            },
        ),
        migrations.CreateModel(
            name='SaleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(default='Seasonal weekly sale 2024', max_length=100)),
                ('subtitle', models.CharField(default='Use code', max_length=200)),
                ('promo_code', models.CharField(default='Sale 2024', max_length=50)),
                ('image', models.ImageField(upload_to='promotions/sales/')),
                ('bg_color_start', models.CharField(default='rgb(172, 203, 238)', max_length=50)),
                ('bg_color_end', models.CharField(default='rgb(231, 240, 253)', max_length=50)),
                ('dark_bg_color_start', models.CharField(default='rgb(27, 39, 58)', max_length=50)),
                ('dark_bg_color_end', models.CharField(default='rgb(31, 38, 50)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sale Banner',
                'verbose_name_plural': 'Sale Banners',
            },
        ),
    ]
