# Generated by Django 5.2.1 on 2025-06-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_headerpromobanner_heroslide_newarrivalsbanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBottomBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='iPad Pro M1', max_length=100)),
                ('subtitle', models.CharField(default='Deal of the week', max_length=200)),
                ('image', models.ImageField(upload_to='promotions/catalog/')),
                ('brand_icon', models.ImageField(blank=True, null=True, upload_to='promotions/icons/')),
                ('bg_color_start', models.CharField(default='rgb(253, 203, 241)', max_length=50)),
                ('bg_color_end', models.CharField(default='rgb(255, 236, 250)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority order (lowest number shows first)')),
            ],
            options={
                'verbose_name': 'Catalog Bottom Banner',
                'verbose_name_plural': 'Catalog Bottom Banners',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='CatalogTopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='iPhone 14', max_length=100)),
                ('subtitle', models.CharField(default='Apple iPhone 14 128GB Blue', max_length=200)),
                ('image', models.ImageField(upload_to='promotions/catalog/')),
                ('price_text', models.CharField(default='From ৳899', max_length=50)),
                ('button_link', models.CharField(default='#', max_length=200)),
                ('bg_color_start', models.CharField(default='rgb(172, 203, 238)', max_length=50)),
                ('bg_color_end', models.CharField(default='rgb(231, 240, 253)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority order (lowest number shows first)')),
            ],
            options={
                'verbose_name': 'Catalog Top Banner',
                'verbose_name_plural': 'Catalog Top Banners',
                'ordering': ['priority'],
            },
        ),
    ]
