# Generated by Django 5.2.1 on 2025-06-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_catalogbottombanner_catalogtopbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogbottombanner',
            name='button_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='catalogbottombanner',
            name='button_text',
            field=models.CharField(default='Shop now', max_length=50),
        ),
    ]
