version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    restart: always
    env_file:
      - backend.env
    volumes:
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    depends_on:
      - db
      - redis
    networks:
      - phonebay_network

  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - phonebay_network

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - db.env
    networks:
      - phonebay_network

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - phonebay_network

  celery:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    restart: always
    command: celery -A backend worker -l info
    env_file:
      - backend.env
    depends_on:
      - db
      - redis
      - backend
    networks:
      - phonebay_network

  celery-beat:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    restart: always
    command: celery -A backend beat -l info
    env_file:
      - backend.env
    depends_on:
      - db
      - redis
      - backend
    networks:
      - phonebay_network

volumes:
  postgres_data:
  redis_data:
  backend_static:
  backend_media:

networks:
  phonebay_network:
    driver: bridge 