version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
      target: backend
    restart: always
    env_file:
      - backend.env
    volumes:
      - ./media:/app/media
      - ./static:/app/staticfiles
    depends_on:
      - db
      - redis
    networks:
      - phonebay_network

  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - frontend.env
    volumes:
      - ./media:/usr/share/nginx/html/media
      - ./static:/usr/share/nginx/html/static
      - /etc/letsencrypt/live/phonebay.xyz/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/phonebay.xyz/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - backend
    networks:
      - phonebay_network

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - phonebay_network

  celery:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
      target: celery
    restart: always
    env_file:
      - backend.env
    volumes:
      - ./media:/app/media
    depends_on:
      - db
      - redis
      - backend
    networks:
      - phonebay_network

  celery-beat:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
      target: celery-beat
    restart: always
    env_file:
      - backend.env
    volumes:
      - ./media:/app/media
    depends_on:
      - db
      - redis
      - backend
    networks:
      - phonebay_network

volumes:
  postgres_data:
  redis_data:

networks:
  phonebay_network:
    driver: bridge 