# Generated by Django 5.2.1 on 2025-06-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: None,
            reverse_code=lambda apps, schema_editor: None,
            hints={'check_table_exists': True},
            atomic=True
        ),

        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Payment'), ('CARD_EMI', 'Card EMI Payment'), ('CARDLESS_EMI_DOWN_PAYMENT', 'Cardless EMI Down Payment'), ('EMI_INSTALLMENT', 'EMI Installment Payment')], default='REGULAR', max_length=30),
        ),
    ]
