# Generated by Django 4.2.8 on 2025-06-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteSettings',
        ),
    ]
