# Generated by Django 4.2.8 on 2025-06-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_delete_websitesettings'),
        ('adminpanel', '0002_sitesettings'),
    ]

    operations = [
    ]
